version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis/redis:/var/lib/redis
      - ./database/redis/redis-config:/usr/local/etc/redis/redis.conf

  sport-informer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis