version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sport-informer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis_data: